config/routes.rb
Eggshell::Application.routes.draw do

  root :to => 'bootstrap#index'

  match '/api/user/status' => 'user_api#status'
  match '/api/user/:uid' => 'user_api#show'
  match '/:fake/api/canvas/mycourses' => 'canvas_api#mycourses'
  match '/api/canvas/mycourses' => 'canvas_api#mycourses'

  match '/auth/cas/callback' => 'sessions#lookup'
  match '/auth/failure' => 'sessions#failure'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login

  match '/*url' => 'bootstrap#index'
end

app/models/user.rb
class User
  include ActiveModel::Serialization
  attr_accessor :uid

  def initialize(uid)
    self.uid = uid
    @calcentral_user_data = UserData.where(:uid => self.uid).first
    @campus_attributes = CampusData.get_person_attributes(self.uid) || {}
    @default_name = @campus_attributes['person_name']
    @override_name = @calcentral_user_data ? @calcentral_user_data.preferred_name : nil
  end

  def preferred_name
    @override_name || @default_name
  end
  def preferred_name=(val)
    if val.blank?
      val = nil
    else
      val.strip!
    end
    @override_name = val
  end

  def save
    if !@calcentral_user_data
      @calcentral_user_data = UserData.create(uid: self.uid, preferred_name: @override_name)
    else
      stored_override = @calcentral_user_data.preferred_name
      if stored_override != @override_name
        @calcentral_user_data.update_attributes(preferred_name: @override_name)
      end
    end
  end

  def update_attributes(attributes)
    if attributes.has_key?(:preferred_name)
      self.preferred_name = attributes[:preferred_name]
    end
    save
  end

end

app/models/user_data.rb
class UserData < ActiveRecord::Base
  attr_accessible :preferred_name, :uid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate
    redirect_to login_url unless session[:user_id]
  end

end

app/controllers/bootstrap_controller.rb
class BootstrapController < ApplicationController

  caches_action(:index)

  def index
  end

end

app/controllers/canvas_api_controller.rb
class CanvasApiController < ApplicationController
  include Fakeable_Proxy

  def mycourses
    unless (params[:fake] == 'fake')
      authenticate
    end

    puts "in CanvasApiController mycourses"
    p params

    # TODO when mycourses is user-specific, add user id to cache key
    response = Rails.cache.fetch("canvas_api_mycourses", :expire_in => 600) do
      do_get("canvas/mycourses", "#{Settings.canvas_proxy.canvas_root}/api/v1/courses",
             {
                 :Authorization => "Bearer #{Settings.canvas_proxy.admin_access_token}"
             }, fake?(params[:fake]))
    end
    render :json => response
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def lookup
    auth = request.env["omniauth.auth"]
    #do something useful with the uid eventually, like check oracle
    session[:user_id] = auth['uid']
    redirect_to '/dashboard', :notice => "Signed in!"
  end

  def destroy
    expire_action(:controller => 'user_api', :action => 'show', :uid => session[:user_id])
    reset_session
    redirect_to "#{Settings.cas_logout_url}?url=#{CGI.escape(request.protocol + request.host_with_port)}"
  end

  def new
    redirect_to '/auth/cas'
  end

  def failure
    redirect_to root_url, :status => 401, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/user_api_controller.rb
class UserApiController < ApplicationController

  caches_action(:show)

  def status
    puts "in UserApiController status"
    p params
    user = get_user(session[:user_id])
    if session[:user_id]
      render :json => {
          :isLoggedIn => true,
          :preferredName => user.preferred_name || "",
          :uid => session[:user_id],
          :widgetData => {}
      }.to_json
    else
      render :json => {
          :isLoggedIn => false
      }.to_json
    end
  end

  def show
    puts "in UserApiController show"
    p params
    user = get_user(params[:uid])
    render :json => {
        :uid => user.uid,
        :preferredName =>  user.preferred_name || ""
    }.to_json
  end

  def get_user(uid)
    Rails.cache.fetch(cache_key(uid)) do
      User.new(uid)
    end
  end

  def cache_key(uid)
    "user_#{uid}"
  end

  # TODO expire is not yet used, but should be called from any code that saves a user
  def expire(uid)
    expire_action(:controller => 'user_api', :action => 'show', :uid => uid)
    Rails.cache.delete(cache_key(uid), :force => true)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bootstrap/index.html.erb
<div data-ng-view></div>

app/views/bootstrap/index_found.html.erb
<!-- Nav Bar -->

  <div class="row">
    <div class="twelve columns">
      <ul class="nav-bar">
        <li class="active"><a href="/">Splash</a></li>
        <li><a href="/dashboard">Dashboard</a></li>
        <li><a href="#">Link 3</a></li>
        <li><a href="#">Link 4</a></li>
      </ul>

      <h1>CalCentral <small>Unified for all student-kind.</small>
      <hr />
    </div>
  </div>

  <!-- End Nav -->


  <!-- Main Page Content and Sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="nine columns" role="content">

      <article>

        <h3><a href="#">Welcome to CalSimple</a></h3>

        <h6>
        <% if user_signed_in? %>
          <%= link_to "Log out", logout_path, :class => 'radius button' -%>
        <% else %>
          <%= link_to "Log in", login_path, :class => 'radius button' -%>
        <% end %>
        </h6>

        <div class="row">
          <div class="six columns">

            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          </div>
          <div class="six columns">
            <img src="http://placehold.it/400x240&text=[img]" />
          </div>
        </div>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

      </article>

      <hr />

      <article>

        <h3><a href="#">Blog Post Title</a></h3>
        <h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>

        <div class="row">
          <div class="six columns">
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          </div>
          <div class="six columns">
            <img src="http://placehold.it/400x240&text=[img]" />
          </div>
        </div>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

      </article>

    </div>

    <!-- End Main Content -->


    <!-- Sidebar -->

    <aside class="three columns">

      <h5>Categories</h5>
      <ul class="side-nav">
        <li><a href="#">News</a></li>
        <li><a href="#">Code</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Fun</a></li>
        <li><a href="#">Weasels</a></li>
      </ul>

      <div class="panel">
        <h5>Featured</h5>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
        <a href="#">Read More &rarr;</a>
      </div>

    </aside>

    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->


  <!-- Footer -->

  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="six columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="six columns">
          <ul class="link-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- End Footer -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-ng-app="calcentral">
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title data-ng-bind="title">Calcentral</title>

  <meta name="description" content="CalCentral is a new resource for the UC Berkeley community." />

  <link rel="icon" href="/assets/favicon.png" type="image/png" />

  <link rel="shortcut icon" href="/assets/favicon.ico" />

  <!-- Included CSS Files -->
  <%= stylesheet_link_tag "application" %>

  <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>

<body class="cc-page-index">

    <%= render 'templates/launcher' %>

    <!-- Top Navbar -->
    <div class="row">
      <ul class="nav-bar">
        <li class="active"><a href="/">Splash</a></li>
        <li><a href="/dashboard">My Dashboard</a></li>
        <li><a href="/secure/campus">My Campus</a></li>
      </ul>
    </div>

      <div class="row cc-container-main" role="main">
        <%= yield %>
      </div>

    <footer class="row">
      <div class="cc-left">Copyright © 2012 The Regents of the University of California</div>
      <a href="#">Help</a>
      <a href="http://ets.berkeley.edu/calcentral-feedback">Feedback</a>
    </footer>

    <%= render 'templates/all' %>

  </body>
</html>

app/views/templates/_all.html.erb
<%= render 'templates/splash' %>
<%= render 'templates/dashboard' %>
<%= render 'templates/profile' %>
<%= render 'templates/error_404' %>